### PR TITLE
Merging Turtle Mode

### PR DESCRIPTION
**Pull request by Rodinga**
The TurtleMode page is functionally complete, but I'll have to clean a few more things up in the next few days. Consider this Beta 1.

### CODE REVIEW

**Comment by TildenG** [comment]
@Rodinga   Are you sure, there are a lot of extra files here & the language files relate to this page only, and no the rest of the project ??

**Comment by Rodinga** [comment]
If you'd prefer to avoid all the extras we can skip everything in the web controls folder. That might need to be done manually though. I'll give it a clean tomorrow as well.

**Comment by TildenG** [comment]
There's no simple way that I can see to drop A folder, I can approve this and you can clean it up in your next update or you could create a new fork with only the relevant files and submit that instead.

**Comment by Rodinga** [comment]
I'll clean it, branch it and you can pull the branch. That should work out.

**Comment by TildenG** [comment]
Ok, thanks, just trying to keep it need as possible, not easy, I know.

**Pull request closed without merging**
